source 'http://rubygems.org'

# Gems to run tests
gem 'calabash-android'
gem 'calabash-cucumber'
gem 'rspec'
gem 'require_all'
gem 'rake' 
gem 'rspec-expectations'
gem 'httparty'

# Gems needed to debug
gem 'byebug'